### ISSUE TITLE
Where is info:update matched?

### ISSUE THREAD

**Issue by bemurphy** [nodezoo/nodezoo-updater#24]
Hi, I've been pouring over the various nodezoo repos for my own education.  Thank you for putting this code up.

I noticed here that there's a call to act including `info:update`:
https://github.com/nodezoo/nodezoo-updater/blob/23a90f9e0e48e766715bfe8bdcee6f7c3c069281/lib/updater.js#L69

I haven't been able to find yet where that pattern is matched.  I'd appreciate if somebody could point me in the right direction.

Thanks for your time in reading this.

**Comment by mihaidma** [comment]
This is the nodezoo architecture: https://github.com/nodezoo/nodezoo-docs/blob/master/doc/architecture.md

There is a dequeue service that is called by the updater: https://github.com/nodezoo/nodezoo-dequeue/blob/027ef6ade333f1fbf51d6984e50916a877dfe20f/lib/dequeue.js#L6

Each service is on its own repo, when you look for pattern matching you have to search across repos located  under the nodezoo organization.

**Comment by bemurphy** [comment]
@mihaidma thank you so much!  This was very helpful and answered my question.
