### ISSUE TITLE
Old node version wanted for npm install

### ISSUE THREAD

**Issue by CodeWriterWriter** [nodezoo/nodezoo-updater#3]
Running npm install gives the following warnings:
WARN engine follow@0.12.1: wanted: {"node":"0.12.x || 0.10.x || 0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})
WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.2.4","npm":"2.14.12"})

**Comment by mcdonnelldean** [comment]
@matt-oc Can you take a look here and see what needs updating?

**Comment by matt-oc** [comment]
@mcdonnelldean No warnings except for one but its not a direct module of this repo. Seneca is a bit out of date but not deprecated.
